remote_theme: MicrosoftLearning/Jekyll-Theme
exclude:
  - readme.md
  - .github/
header_pages:
  - index.html
author: Learning Service
twitter_username: LSlearning
github_username:  LearningService
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
title: Lab Exercises Assistant
